### ISSUE TITLE
Half day absence / Hald day sick / Fill worktime

### ISSUE THREAD

**Issue by marcaurele** [adfinis/timed-frontend#1079]
Hi,

I was playing with the tool and was wondering what was the differentiator with the flag `fill worktime` on Absence model?.

How users are supposed to enter half-day of holidays for example? I see that only absences without the `fill worktime` can have a positive credits (annual leave allowance) which gets decreased by how many such _full_ absences are taken.

Same for sickness, how are users supposed to report half afternoon sickness? Should this absence type be flagged as `fill worktime`?

**Comment by trowik** [comment]
Hi,

Thanks for the question.

With `fill_worktime` you can define, if you want to fill the work day with the absence based on the already reported time. This is based on the `worktime_per_day` set in an employment. So the time of the absence either fills the `worktime_per_day` or has the duration of `worktime_per_day`

I'll give you an example:
You have an employment of 8h/day. 
1) You work 4 hours and by adding an absence you fill the remaining 4 hours with it.
or
2) You work 2 hours and additionally create an absence for that day. The absence time is then set by the `worktime_per_day`

Number 1 results in 4h work time, 4h absence.
Number 2 results in 2h work time, 8h absence.

I hope that answers your questions. :)

**Comment by marcaurele** [comment]
Thanks I understand better how the `fill worktime` works.

I'm still having a hard time to understand how to setup the vacations for example. With an employment, each person gets an allowance beginning of the year of let's say 25 days. So in order to put a positive credit balance, the absence type "vacations" must not have the `fill worktime` checked. This works fine for full day of vacations. But how do you do with 1/2 days? The 4hours would be seen as extra work?

**Comment by trowik** [comment]
As of now, having half day vacations using the credit balance, is not possible.
You'd have to activate `fill worktime` and keep track of the amount of hours a user could spend for vacations. That would require some manual work. like calculating the max amount of hours for vacations and verifying it with the current amount.

**Comment by marcaurele** [comment]
Thanks @trowik! This was my guess too but wanted to double check. I might work on an improvement one day.
