### ISSUE TITLE
Feat: "magic links"

### ISSUE THREAD

**Issue by StephanH90** [adfinis/timed-frontend#681]
It would be cool if we could have magic links, ie I can select something in timed, have a btn that I can click which generates me a link which, when sent to somebody, will create a new entry under "Timesheet" where they just have to enter the hours and text.

This could be extended where I can even specify the time and text when creating the magic link. The person just has to click the link and press save.

**Comment by derrabauke** [comment]
Implemented by https://github.com/adfinis/timed-frontend/pull/1022

**Comment by trowik** [comment]
When setting query params for `not billable` or `needs review` (either to false or true) sets the according flag in GUI after using the magic link.

Steps to reproduce:
- open magic link creator
- select Customer etc.
- select one of `needs review` or `not billable` flag
- unselect the chosen flag
- magic link creator creates a link to a report with that flag set to `false`
- opening the link creates a "draft" report with that flag set to `true`

You can still unselect the flag before saving, but that's an extra step that shouldn't happen.

**Comment by StephanH90** [comment]
this has been fixed in #1046
