### ISSUE TITLE
Incorrect number of hours in worktime balance mouseover

### ISSUE THREAD

**Issue by tongpu** [adfinis/timed-frontend#691]
When my worktime balance is negative I often have the issue that the exact number shown in the hover always shows 0h 0m, instead of the correct balance on that day. This only happens if my balance is negative, I never saw it when it was positive.

![image](https://user-images.githubusercontent.com/2674075/182359334-22259018-359c-4105-b7a3-5a217b69c30f.png)

**Comment by derrabauke** [comment]
Seems to be fixed after the latest ember-upgrading efforts. Please verify on `test`. :)

**Comment by tongpu** [comment]
Looks fine on test, so this might have been fixed.
