### ISSUE TITLE
Bugs in new timed release

### ISSUE THREAD

**Issue by C0rydoras** [adfinis/timed-frontend#799]
# Timesheet
* This got fixed while i was testing (see https://github.com/adfinis/timed-backend/pull/928)
  * ~~Creating a new report does not work, the problem seems to be, that remaining-effort is null~~
    *   ~~{"errors":[{"detail":"This field may not be null.","status":"400","source":{"pointer":"/data/attributes/remaining-effort"},"code":"null"}]}~~
  *  ~~The same applies to changing a reports customer/project/task (i tested this on reports created using the generate timesheet button)~~
* Rescheduling
   *  When rescheduling a day with verified events, it works, but you get this error message: ![image](https://user-images.githubusercontent.com/110528300/217778611-59020a10-116d-4398-85a5-996664647358.png)
      * this also applies to the current timed.
      * the diagram (weekly-overview) also does not update, even though the timesheet was rescheduled, after a refresh/switching to another day/pressing the save button again the diagram updates
# Absences
* After adding one or multiple absences they are not displayed until a refresh/switching day
* After removing an absence, when trying to create a new absence (on the same day), the current day is selected and disabled, and therefore cannot be deselected.
# Analysis
* When sorting the Total time changes to 0 and then back. It does always stay the same since its the total.
# Activities
* The record-button has no icon
* In the "Activities contain unknown tasks" modal the "thats fine" button is missing the margin right
   * test: ![image](https://user-images.githubusercontent.com/110528300/217775727-b27352dd-26d3-45e7-b45b-053b18d7d89d.png)
   * normal: ![image](https://user-images.githubusercontent.com/110528300/217775972-5e9277d0-3004-4301-8870-358dbd1fff32.png)

**Comment by derrabauke** [comment]
Thanks for the feedback! :pray: 

## Activities
* Is this the record button you are refer to? The button seems to be visible on my side. Maybe try clearing the cache once.
![image](https://user-images.githubusercontent.com/10029904/217818105-53c0d062-d909-4932-8684-1ce6d5adfbe7.png)

**Comment by C0rydoras** [comment]
Sadly that did not resolve the issue. It still remains without an icon for me.

**Comment by C0rydoras** [comment]
In this case the icon is not just missing for me but also for other people.

**Comment by trowik** [comment]
similar issue with the record button:

![image](https://user-images.githubusercontent.com/55092761/218063469-17976d07-b6fa-4165-a8fc-d82ed7ef65d7.png)

**Comment by derrabauke** [comment]
@trowik @C0rydoras Which browser do you use?

Can't reproduce on Chromium (Version 109.0.5414.119) nor FF (109.0.1). :man_shrugging:

**Comment by trowik** [comment]
@derrabauke using Firefox 109.0.1 as well...
I'll check the behaviour with other browsers later

**Comment by C0rydoras** [comment]
@derrabauke 
I tested it on Chrome (Version 109.0.5414.119 (Official Build) (64-bit)) 
and Firefox (Version 109.0.1)

**Comment by derrabauke** [comment]
> # Timesheet
> * Rescheduling
>   
>   * When rescheduling a day with verified events, it works, but you get this error message: ![image](https://user-images.githubusercontent.com/110528300/217778611-59020a10-116d-4398-85a5-996664647358.png)
>     
>     * this also applies to the current timed.
>     * the diagram (weekly-overview) also does not update, even though the timesheet was rescheduled, after a refresh/switching to another day/pressing the save button again the diagram updates
> 

Splitting it up for better issue tracking

**Comment by derrabauke** [comment]
> # Absences
> * After adding one or multiple absences they are not displayed until a refresh/switching day
> * After removing an absence, when trying to create a new absence (on the same day), the current day is selected and disabled, and therefore cannot be deselected.

Splitting it up for better issue tracking

**Comment by derrabauke** [comment]
Everything got resolved. Please check next deployment (tomorrow) for regressions. ;)
