### ISSUE TITLE
Budget check timed bot - not working

### ISSUE THREAD

**Issue by rafahu** [adfinis/timed-frontend#801]
Hi @trowik 

You and I worked together to link [this test project](https://test.project.adfinis.com/issues/1295?tab=history) and Customer "Partners Group > Rafaela Testing". 

Having logged 31% of hours on Feb 9th, this should have triggered the alert, but I do not see any email in my inbox or any text description in the ticket. Not sure where it went wrong.

**Comment by trowik** [comment]
Hi @rafahu 

I noticed that no notification was sent and I'm looking into it.

**Comment by trowik** [comment]
Hey @rafahu
Fixed the bug and it looks like the bot is working as intended.
Emails from our test apps aren't sent to you directly though, therefore you shouldn't get any. But they would trigger. (I think you have the watch the ticket in Redmine as far as I know)

**Comment by rafahu** [comment]
Super! @trowik should I log enough hours to pass the 70% threshold and see what happens?

and yes, I think the email is triggered by Redmine to all people following and not actually from Timed

**Comment by trowik** [comment]
Sure @rafahu . That would be perfect.

**Comment by trowik** [comment]
70% threshold works as well. All notifications from the bot were sent only once.
