### ISSUE TITLE
bug: remaining effort - reject not enabled in some cases

### ISSUE THREAD

**Issue by derrabauke** [adfinis/timed-frontend#806]
# Description
A user with *sufficient permissions* (who is a reviewer for a certain report) should be able to reject the report in the analysis view.

# Expected behavior
The report can get rejected via the `reject` checkbox

# Actual behavior
The `reject` checkbox is always disabled.

# Notes
This was initally submitted in #800 by @rafahu

**Comment by derrabauke** [comment]
I could not reproduce the described behavior. @rafahu, could you elaborate how you tried to test it? Are you sure, you should be allowed to reject the given report?

![image](https://user-images.githubusercontent.com/10029904/218723369-9d45089c-77a7-4150-850c-ae9bf416aa17.png)

**Comment by rafahu** [comment]
@derrabauke 

I've tried to tick the reject box for several projects I'm reviewer for and the box is greyed out.

Here's an example
![image](https://user-images.githubusercontent.com/113115754/218724681-73ef1d9f-5292-4836-9bb2-6d72e1c60cbf.png)

**Comment by derrabauke** [comment]
You are trying to reject your own report, which is not possible. Please try to edit/reject the report @trowik submitted.
![image](https://user-images.githubusercontent.com/10029904/218734410-2006f843-f44e-4f0f-8be6-d8690236febc.png)

**Comment by rafahu** [comment]
Ha! it works @derrabauke :)
