### ISSUE TITLE
bug: rescheduling

### ISSUE THREAD

**Issue by derrabauke** [adfinis/timed-frontend#807]
> * Rescheduling
>   
>   * When rescheduling a day with verified events, it works, but you get this error message: ![image](https://user-images.githubusercontent.com/110528300/217778611-59020a10-116d-4398-85a5-996664647358.png)
>     
>     * this also applies to the current timed.
>     * the diagram (weekly-overview) also does not update, even though the timesheet was rescheduled, after a refresh/switching to another day/pressing the save button again the diagram updates
> 

Splitting it up for better issue tracking

_Originally posted by @derrabauke in https://github.com/adfinis/timed-frontend/issues/799#issuecomment-1429585798_

**Comment by derrabauke** [comment]
This seems to be a backend issue. See https://github.com/adfinis/timed-backend/issues/930

**Comment by trowik** [comment]
You can't reschedule verified reports.
At first the frontend shows, as if the reports were rescheduled, but once the page is refreshed, the reports are still there.

**Comment by derrabauke** [comment]
> You can't reschedule verified reports.
They weren't verified yet. Really tricky this thingy ;)

**Comment by derrabauke** [comment]
Short note: 
* verified reports can not be rescheduled
* atm the UX is not very good and we have to improve the handling of this situation
* the frontend should never show wrong data (rescheduled reports which can not get rescheduled)
