### ISSUE TITLE
Most used tasks and projects

### ISSUE THREAD

**Issue by trowik** [adfinis/timed-frontend#839]
Most used tasks and projects appear at the top of the selection and not in alphabetical order.

![image(1)](https://user-images.githubusercontent.com/55092761/221785491-2848a743-35ee-4345-b1e0-b9f8ccd430a6.png)

Could be connected to #838

**Comment by derrabauke** [comment]
AFAIK this is intended behavior. Or I don't understand the report correctly.

**Comment by trowik** [comment]
AFAIK the most used once should only appear in the customer selection and not in the other ones

**Comment by derrabauke** [comment]
:eyeglasses: reading carefully. `noted` I will investigate into the issue!

**Comment by derrabauke** [comment]
Fixed.
