### ISSUE TITLE
Cannot assign project or task assignee in django frontend

### ISSUE THREAD

**Issue by Daenou** [adfinis/timed-frontend#847]
Since the newest update I can't set assign assignees to projects or tasks in the django frontend (/admin).

![2023-02-28-184411_497x274_scrot](https://user-images.githubusercontent.com/29140988/221935918-708c8094-024a-471c-b690-0d42b2eafb97.png)

**Comment by trowik** [comment]
That's a permission issue. 
Since the update new searchable dropdown makes a request to get the users and you need permission for that.
I'll inform our admin on how to correctly update permissions.
