### ISSUE TITLE
Improve visual indicators for (non-)billable and needs-review

### ISSUE THREAD

**Issue by martinwe-adfinis** [adfinis/timed-frontend#858]
In the timesheet view, the visual indication for whether a task is billable or not is difficult to see due to the low colour contrast.
![2023-03-02_133624](https://user-images.githubusercontent.com/95877539/222522009-82936e04-8c65-4502-bde6-3175aa6e962a.png)

In the activity and review view, this is slightly better, but still difficult to see (mainly due to unchecked boxes also having a thick/strong border):
![2023-03-02_150740](https://user-images.githubusercontent.com/95877539/222522497-a060a44b-f11b-4919-98fc-ba476ea9b450.png)

In both cases, would it be possible to increase the difference between checked/unchecked?

Thanks!

**Comment by MitanOmar** [comment]
sure
