### ISSUE TITLE
Edit Form doesn't update when selecting another entry and can't be saved either

### ISSUE THREAD

**Issue by Melkor333** [adfinis/timed-frontend#859]
When changing activity in the "activities" tab to edit them, the "edit" menu doesn't properly update.
Reproduce with:

- Go to Tracking -> Activities
- Make sure there are 2 entries
- Click on the first entry so that the edit menu appears on the right
- click on the second entry.

What happens:
- The description and start/end times get updated
 - the customer/project/task are still from the first entry
 - the apply button stays gray when changing something.

Browser used: Firefox

**Comment by fadnincx** [comment]
At least according to the logo, I have 3.0.2 available, but still I have can reproduce this issue.

(Browser user: Firefox)
