### ISSUE TITLE
Negative Attendance Possible

### ISSUE THREAD

**Issue by C0rydoras** [adfinis/timed-frontend#881]
## Issue
It is possible to set negative attendance time
![image](https://user-images.githubusercontent.com/110528300/226893636-4023e82d-2d4b-4f62-80d8-580110e17d05.png)
## Steps to reproduce
- Go to the attendances tab
- Zoom in until the bar gets replaced by 2 Inputs
![image](https://user-images.githubusercontent.com/110528300/226895998-3c9f023c-b55a-400b-aef6-f984ac27fe26.png)
- These inputs are not validated for negative values. Therefore, negative values can be achieved by setting the second inputs value lower than the first inputs value.
![image](https://user-images.githubusercontent.com/110528300/226895577-e9bfde01-8521-444f-8b71-083a0ea88234.png)

**Comment by MitanOmar** [comment]
fixed, and the fix will be available in the next release
