### ISSUE TITLE
Total Attendance Time 1 minute too low

### ISSUE THREAD

**Issue by C0rydoras** [adfinis/timed-frontend#882]
## Issue
The Time shown was always 1 minute off (also when changing the attendance)
![image](https://user-images.githubusercontent.com/110528300/227135460-54ae96bb-d4a6-4004-aa99-71a653620ce6.png)

I haven't been able to reproduce it, after refreshing it worked as intended again.

**Comment by derrabauke** [comment]
Please reopen if this is reproducible after `v3.1.1`.
