### ISSUE TITLE
Attendance Time is not rounded Correctly

### ISSUE THREAD

**Issue by C0rydoras** [adfinis/timed-frontend#890]
## Issue
![image](https://user-images.githubusercontent.com/110528300/228561179-4359be09-3b2f-40aa-b640-37140393488b.png)
![image](https://user-images.githubusercontent.com/110528300/228561511-0c71cbc7-1ce2-4dc7-af31-6079cc6a2da6.png)

## How to reproduce
* This happened during normal use of the Bar.
* This is not the same as [this](#882) with the difference being that in this case the time is not displayed in a wrong way but is actually saved wrongly, in the case of [this](#882) the time displayed was always 1 Minute too low, even when changing the attendance time.

**Comment by derrabauke** [comment]
Sorry, but I can not reproduce with *normal use of the bar*. Which version of *timed* are you using? How on earth could you get `03:08` and `02:56` durations? O.o

**Comment by C0rydoras** [comment]
timed version v3.0.2
I *aggressively dragged the bar*

I do still have the Attendances saved:
![image](https://user-images.githubusercontent.com/110528300/229517640-35242975-5459-4cf1-84bc-9f0600cc1864.png)
I tried reproducing this for about 20 minutes but was unsuccessful.

**Comment by derrabauke** [comment]
> timed version v3.0.2 I _aggressively dragged the bar_
> 
> I tried reproducing this for about 20 minutes but was unsuccessful.

I will close for now, since not reproduceable. But if you manage to reproduce it properly in the next release `v3.1.1`, please reopen the ticket. Thanks :star2:
