### ISSUE TITLE
Report Suggestions broken

### ISSUE THREAD

**Issue by C0rydoras** [adfinis/timed-frontend#891]
## Issue

When selecting a Report path (e.g. Some Customer > Some Project > Some Task) twice in a row, the second one only sets the customer

https://user-images.githubusercontent.com/110528300/228574856-bb12f22f-4b00-485f-8e97-d40c9c43c63d.mp4

## How to reproduce
1. Select a report path
2. Select another report path for the same report

**Comment by derrabauke** [comment]
Alright. Thanks for the verification. Will fix it asap. :+1:
