### ISSUE TITLE
bug: SSO token handling

### ISSUE THREAD

**Issue by smirta** [adfinis/timed-frontend#907]
The SSO token handling still feels degraded compared to before the last big update end of February. The frontend stays active but is no longer able to access the backend du to an expired token. This sometimes leads to the situation that changes can't be written and are lost after a refresh of the page that redirects to the oidc auth. Other pages of course also misbehave because of this behavior.

At least, I'd expect the frontend to redirect to oidc auth as soon as the token's expired. Even cooler would be to cache unsaved changes somehow and keep them until re-authentication. Don't know if that is possible.

**Comment by derrabauke** [comment]
The current release should have improved the situation. We will investigate a little further. Sorry for the inconvenience.

Connected to #867

**Comment by derrabauke** [comment]
Caused by [a bug in ember-simple-auth-oidc](https://github.com/adfinis/ember-simple-auth-oidc/pull/761).
